### ISSUE TITLE
What if a middleware throws?

### ISSUE THREAD

**Issue by pke** [zach-waggoner/redux-saga-rest#2]
Is that supported, that a middleware, lets say a json middleware, throws if the response is not json?

```es6
const toJson = () => function* (req, next) {
  const response = yield next(new Request(req))
  try {
     return response.convertToJson()
  } catch (e) {
    throw new Error("Not a json response")
  }
}


try {
  const json = yield auth.get('/profile/')
  yield put(success(json))
} catch (e) {
  yield put(error(e))
}
```

**Comment by jurby** [comment]
Yes, I use like this:

_jsonMiddlewareSaga.js_
`
// @flow

import { put, select } from 'redux-saga/effects'
import { API } from 'redux-saga-rest'

const jsonMiddlewareSaga = () => function* (req, next) {
    const response = yield next(new Request(req))
    try {
        return yield response.json()
    } catch (e) {
        throw new Error("Not a json response")
    }
}

export default jsonMiddlewareSaga
`

_apiSaga.js_
`
// @flow

import { put, select } from 'redux-saga/effects'
import { API } from 'redux-saga-rest'
import Config from 'react-native-config'

import authMiddlewareSaga from './authMiddlewareSaga'
import defaultApiMiddlewareSaga from './defaultApiMiddlewareSaga'
import jsonMiddlewareSaga from './jsonMiddlewareSaga'
import errorHandlingMiddlewareSaga from './errorHandlingMiddlewareSaga'

const CLIENT_API_URL = `${Config.CLIENT_API_URL}`

export const client = new API(`${CLIENT_API_URL}`)
    .use(authMiddlewareSaga())
    .use(errorHandlingMiddlewareSaga())
    .use(defaultApiMiddlewareSaga())
    .use(jsonMiddlewareSaga())
`

Beware, every middleware that works with the answer must return a response. Json middleware must be the last time since `response.json()` can only be called once.

**Comment by pke** [comment]
No longer using redux-saga.
